name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]
permissions:
  id-token: write
  contents: read

jobs:
  terraform-Iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590183704678:role/aws-terraform-developer
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: List files in the workspace
        run: ls -R

      - run: terraform init
        working-directory: basic-vpc/

      - run: terraform destroy -auto-approve
        working-directory: basic-vpc/